### PR TITLE
Feature/clarify capabilities

### PR DESCRIPTION
**Pull request by tbowmo**
Clarify capabilities json object, as it was a bit unclear what the different entries where supposed to be showing.

Also fixed issue with toggling pause, as it used a wrong parameter in ChromeState (which showed if pause where possible)

### CODE REVIEW

**Comment by tbowmo** [comment]
@Stanback Could you give this one a spin at your end? And see if it breaks things

(Sorry, for using you as a review peer / Guineapig :) )

**Comment by Stanback** [comment]
@tbowmo Sure thing :smile: will test it when I get home from work today

**Comment by Stanback** [comment]
@tbowmo Just tested - it's working well for me 👍

**Comment by tbowmo** [comment]
ok, then I'll let it go in then.. should be the last bigger restructuring pr..

**Pull request merged**
